"""init

Revision ID: 8e2bcb1a422a
Revises: 
Create Date: 2023-04-22 17:53:35.046808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2bcb1a422a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_seen', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('history',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=255), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('valuer_id', sa.UUID(), nullable=False),
    sa.Column('evaluated_user_id', sa.UUID(), nullable=False),
    sa.Column('action_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluated_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['valuer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('action_id'),
    sa.UniqueConstraint('valuer_id', 'evaluated_user_id', name='_valuer_id_evaluated_user_id_UC')
    )
    op.create_table('photos',
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('photo_path', sa.TEXT(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    op.drop_table('history')
    op.drop_table('users')
    # ### end Alembic commands ###
